### ISSUE TITLE
uniform이면 1단위로 Grid Search 하나요?

### ISSUE THREAD

**Issue by ZiminPark** [jsrimr/nni_toy#1]
uniform이면 1단위로 Grid Search 하나요?
nni들어가서 보려 했는데 잘 모르겠네요.
저도 어제 Bayesian Optimization 처음 써봐서 급 AutoML에 관심이 생겼네요 ㅋㅋ

**Comment by jsrimr** [comment]
```
-   params = {'data_dir': '/tmp/tensorflow/mnist/input_data', 'dropout_rate': 0.5, 'channel_1_num': 32, 'channel_2_num': 64,
-   'conv_size': 5, 'pool_size': 2, 'hidden_size': 1024, 'learning_rate': 1e-4, 'batch_num': 2000, 'batch_size': 32}
+ {
+     "dropout_rate":{"_type":"uniform","_value":[0.5, 0.9]},
+     "conv_size":{"_type":"choice","_value":[2,3,5,7]},
+     "hidden_size":{"_type":"choice","_value":[124, 512, 1024]},
+     "batch_size": {"_type":"choice", "_value": [1, 4, 8, 16, 32]},
+     "learning_rate":{"_type":"choice","_value":[0.0001, 0.001, 0.01, 0.1]}
+ }
```
uniform 이랑 choice 랑 반대되는 개념으로 보시면 될 거 같아요~ choice 는 저중에 하나 고르기 uniform 은 range 안에서 고르기(?)

제가 알기로 Grid Search 따로 있고, Bayesian 방식의 search 따로 있는 걸로 아는데 Tuner 가 TPE 라고 해서 베이지안 방식으로 search 하는 걸로 알고 있어요!

```
authorName: default
experimentName: example_nni
trialConcurrency: 32
maxExecDuration: 1h
maxTrialNum: 10000
trainingServicePlatform: local
# The path to Search Space
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
# The path and the running command of trial
trial:
  command: /home/jeffrey/anaconda3/envs/nni/bin/python hyojun.py
  codeDir: .
  gpuNum: 0
```

참고 : https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/QuickStart.md
